--- 
document: 
  description: |
    Il manuale è uno strumento di lavoro per la Pubblica Amministrazione e serve ad orientare la progettazione
    di ambienti digitali fornendo indicazioni relative al service design, alla user research, al content design
    e alla user interface.
  name: "Manuale operativo di design"
  tags: 
    - design
